INSERT INTO med_medicamentos (medic_nome) VALUES ('A CURITYBINA');
INSERT INTO med_medicamentos (medic_nome) VALUES ('ABLOK');
INSERT INTO med_medicamentos (medic_nome) VALUES ('ACEBROFILINA');
INSERT INTO med_medicamentos (medic_nome) VALUES ('AGUA PARA INJETAVEIS');
INSERT INTO med_medicamentos (medic_nome) VALUES ('AMOXICILINA');
INSERT INTO med_medicamentos (medic_nome) VALUES ('BACINA');
INSERT INTO med_medicamentos (medic_nome) VALUES ('BART H');
INSERT INTO med_medicamentos (medic_nome) VALUES ('BENEGRIP');
INSERT INTO med_medicamentos (medic_nome) VALUES ('BENZETACIL');
INSERT INTO med_medicamentos (medic_nome) VALUES ('BOTOX');
INSERT INTO med_medicamentos (medic_nome) VALUES ('CATIVA');
INSERT INTO med_medicamentos (medic_nome) VALUES ('CEFALEXINA');
INSERT INTO med_medicamentos (medic_nome) VALUES ('CETOCONAZOL');
INSERT INTO med_medicamentos (medic_nome) VALUES ('CETOPROFENO');
INSERT INTO med_medicamentos (medic_nome) VALUES ('CLORDILON');
INSERT INTO med_medicamentos (medic_nome) VALUES ('DESOL');
INSERT INTO med_medicamentos (medic_nome) VALUES ('DETAMAX');
INSERT INTO med_medicamentos (medic_nome) VALUES ('DIABEMED');
INSERT INTO med_medicamentos (medic_nome) VALUES ('DIAZEPAM');
INSERT INTO med_medicamentos (medic_nome) VALUES ('DIPIRONA SODICA');
INSERT INTO med_medicamentos (medic_nome) VALUES ('EQUITAM');
INSERT INTO med_medicamentos (medic_nome) VALUES ('ERANZ');
INSERT INTO med_medicamentos (medic_nome) VALUES ('ERBITUX');
INSERT INTO med_medicamentos (medic_nome) VALUES ('ERITROMAX');
INSERT INTO med_medicamentos (medic_nome) VALUES ('ESC');
